#!/bin/bash -l
#
#Number of cores requested
#$ -pe omp 12

#Give the name to the job
#$ -N blast_Query

#Send an email when the job is finished (or aborted)
#$ -m ae

#Join the error and output file
#$ -j y


# Set the runtime limit (default 12 hours):
#$ -l h_rt=12:00:00

# Specify your project
#$ -P ct-shbioinf


# Stuff to execute: 


module load blast+ #load blast module
module load R/3.6.2 #load R3.6.2
module load sratoolkit

cd /projectnb/ct-shbioinf/awillia5/Applied-Bioinformatics #use your notes or project folder. Wherever your script is located

Rscript 'Code/rBLAST.R' #run the script